window.ENROOT_CARDS=(window.ENROOT_CARDS||[]).concat([
  {
    "word": "accommodate",
    "zh": "容納、提供住宿",
    "rarity": "R",
    "origin": "16 世紀｜拉丁語",
    "route": "Latin accommodare → accommodate",
    "root": "ad＝向＋commod＝合適、方便",
    "story": "accommodate 原本帶有「使某事適合、調整到合宜位置」的概念，後來延伸成提供空間、容納或住宿。",
    "tag": "TOEIC",
    "scene": "accommodate"
  },
  {
    "word": "reimburse",
    "zh": "報銷、償還",
    "rarity": "R",
    "origin": "17 世紀｜法語",
    "route": "French rembourser → reimburse",
    "root": "re＝回＋bourse＝錢包",
    "story": "reimburse 的畫面很直接：把錢放回某人的錢包，因此成為報銷與償還費用。",
    "tag": "TOEIC",
    "scene": "reimburse"
  },
  {
    "word": "itinerary",
    "zh": "行程表",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "Latin itinerarium → itinerary",
    "root": "iter＝旅程、道路",
    "story": "itinerary 源自表示旅程與道路的拉丁語，後來固定用來指旅行路線與行程安排。",
    "tag": "旅遊",
    "scene": "itinerary"
  },
  {
    "word": "maintenance",
    "zh": "維護、保養",
    "rarity": "R",
    "origin": "中世紀法語",
    "route": "maintenir → maintenance",
    "root": "main＝手＋tenir＝握住",
    "story": "maintenance 與 maintain 同源，核心畫面是「用手維持住」，因此引申為保養、維護與保持運作。",
    "tag": "TOEIC",
    "scene": "maintenance"
  },
  {
    "word": "prerequisite",
    "zh": "先決條件",
    "rarity": "SR",
    "origin": "17 世紀｜拉丁語構詞",
    "route": "pre + requisite → prerequisite",
    "root": "pre＝之前＋requisite＝必要之物",
    "story": "prerequisite 就是「在事情開始之前就必須具備的條件」，構詞邏輯幾乎等於字義。",
    "tag": "學術",
    "scene": "prerequisite"
  },
  {
    "word": "subsidiary",
    "zh": "子公司、附屬機構",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "Latin subsidiarius → subsidiary",
    "root": "subsidium＝支援、後備",
    "story": "subsidiary 早期有「支援、後備」的意思，商業上逐漸成為由母公司控制的附屬公司。",
    "tag": "商務",
    "scene": "subsidiary"
  },
  {
    "word": "consecutive",
    "zh": "連續的",
    "rarity": "R",
    "origin": "拉丁語",
    "route": "consequi（跟隨）→ consecutive",
    "root": "con＝一起＋sequ＝跟隨",
    "story": "consecutive 的核心是「一個跟著一個」，所以表示連續發生、不中斷。",
    "tag": "學術",
    "scene": "consecutive"
  },
  {
    "word": "complimentary",
    "zh": "免費贈送的、讚美的",
    "rarity": "SR",
    "origin": "拉丁語／法語",
    "route": "compliment → complimentary",
    "root": "compliment＝致意、稱讚",
    "story": "complimentary 一方面表示稱讚性的，另一方面在飯店與商務語境常表示出於禮貌免費提供。",
    "tag": "TOEIC",
    "scene": "complimentary"
  },
  {
    "word": "discrepancy",
    "zh": "差異、不一致",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "discrepare → discrepancy",
    "root": "dis＝分開＋crepare＝發出聲響",
    "story": "discrepare 原本可指聲音不協調，後來 discrepancy 便發展成資料、帳目或說法彼此不一致。",
    "tag": "商務",
    "scene": "discrepancy"
  },
  {
    "word": "feasible",
    "zh": "可行的",
    "rarity": "R",
    "origin": "15 世紀｜法語",
    "route": "French faisable → feasible",
    "root": "faire＝做",
    "story": "feasible 的核心就是「做得到」。它比單純 possible 更常強調實務上可執行。",
    "tag": "學術",
    "scene": "feasible"
  },
  {
    "word": "mandatory",
    "zh": "強制的、必須的",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "mandatum（命令）→ mandatory",
    "root": "mand＝命令、託付",
    "story": "mandatory 和 mandate 同源，核心都和命令有關，所以表示依法或依規定必須完成。",
    "tag": "TOEIC",
    "scene": "mandatory"
  },
  {
    "word": "expedite",
    "zh": "加速、促進",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "expeditus（脫離束縛、準備好）→ expedite",
    "root": "ex＝脫離＋ped＝腳",
    "story": "expeditus 有「腳不再受束縛、可以迅速行動」的畫面，後來 expedite 便成為加速處理。",
    "tag": "商務",
    "scene": "expedite"
  },
  {
    "word": "allocate",
    "zh": "分配、配置",
    "rarity": "R",
    "origin": "拉丁語",
    "route": "ad + locare → allocate",
    "root": "ad＝向＋loc＝位置",
    "story": "allocate 的畫面是把資源放到指定位置，因此成為分配預算、人力與資源的常用字。",
    "tag": "TOEIC",
    "scene": "allocate"
  },
  {
    "word": "comply",
    "zh": "遵守、依從",
    "rarity": "R",
    "origin": "義大利語／拉丁語",
    "route": "Italian complire → comply",
    "root": "com＝一起＋plere＝填滿、完成",
    "story": "comply 的歷史語義與完成要求、配合有關，現代最常見就是遵守規定或要求。",
    "tag": "TOEIC",
    "scene": "comply"
  },
  {
    "word": "procurement",
    "zh": "採購",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "procurare → procure → procurement",
    "root": "pro＝為了＋cur＝照料",
    "story": "procurement 不只是買東西，而是替組織取得並管理所需資源，因此常見於企業與政府採購。",
    "tag": "商務",
    "scene": "procurement"
  },
  {
    "word": "liability",
    "zh": "責任、負債",
    "rarity": "SR",
    "origin": "法語／拉丁語",
    "route": "liable → liability",
    "root": "ligare＝綁、約束",
    "story": "liability 的核心是「被責任綁住」。法律上是責任，會計上則常表示負債。",
    "tag": "金融",
    "scene": "liability"
  },
  {
    "word": "vacancy",
    "zh": "空缺、空房",
    "rarity": "R",
    "origin": "拉丁語",
    "route": "vacare（空著）→ vacancy",
    "root": "vac＝空",
    "story": "vacancy 直接保留「空著」的概念，所以可以是職缺，也可以是旅館空房。",
    "tag": "TOEIC",
    "scene": "vacancy"
  },
  {
    "word": "payroll",
    "zh": "薪資表、薪資總額",
    "rarity": "R",
    "origin": "英語",
    "route": "pay + roll → payroll",
    "root": "pay＝支付＋roll＝名冊",
    "story": "早期 roll 可以指名冊或捲軸，payroll 因而成為要支付薪資的人員名冊與薪資總額。",
    "tag": "商務",
    "scene": "payroll"
  },
  {
    "word": "acquisition",
    "zh": "取得、收購",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "acquirere → acquisition",
    "root": "ad＝向＋quir＝取得",
    "story": "acquisition 的核心是「取得」。在商務新聞中最常見的高階義就是企業收購。",
    "tag": "商務",
    "scene": "acquisition"
  },
  {
    "word": "quotation",
    "zh": "報價、引文",
    "rarity": "R",
    "origin": "拉丁語",
    "route": "quotare（標記數目）→ quote → quotation",
    "root": "quot＝多少、數量",
    "story": "quotation 可指引用的文字，也可指價格報價；兩者都帶有把內容明確列出、標示的概念。",
    "tag": "TOEIC",
    "scene": "quotation"
  },
  {
    "word": "reschedule",
    "zh": "重新安排時間",
    "rarity": "N",
    "origin": "英語構詞",
    "route": "re + schedule → reschedule",
    "root": "re＝重新＋schedule＝時間表",
    "story": "reschedule 就是把原本的時間表重新排一次，是最透明、最適合用字首理解的商務字。",
    "tag": "TOEIC",
    "scene": "reschedule"
  },
  {
    "word": "subscription",
    "zh": "訂閱、訂購",
    "rarity": "R",
    "origin": "拉丁語",
    "route": "subscribere → subscription",
    "root": "sub＝在下＋script＝寫",
    "story": "subscription 早期和「在文件下方簽名」相關，後來延伸為簽署加入、持續訂閱服務。",
    "tag": "商務",
    "scene": "subscription"
  },
  {
    "word": "forecast",
    "zh": "預測",
    "rarity": "R",
    "origin": "古英語構詞",
    "route": "fore + cast → forecast",
    "root": "fore＝之前＋cast＝投擲",
    "story": "forecast 像是把判斷投向前方、未來，因此成為天氣、營收與需求預測。",
    "tag": "TOEIC",
    "scene": "forecast"
  },
  {
    "word": "brochure",
    "zh": "宣傳小冊",
    "rarity": "R",
    "origin": "法語",
    "route": "French brochure → brochure",
    "root": "brocher＝裝訂、縫合",
    "story": "brochure 原本和把紙頁簡單裝訂成冊有關，後來專指宣傳或介紹用的小冊子。",
    "tag": "TOEIC",
    "scene": "brochure"
  },
  {
    "word": "receipt",
    "zh": "收據、收到",
    "rarity": "R",
    "origin": "拉丁語／法語",
    "route": "recipere → receite → receipt",
    "root": "re＝回＋cip/cept＝拿",
    "story": "receipt 與 receive 同源，核心都是「收到」。付款後拿到的證明，自然成為收據。",
    "tag": "TOEIC",
    "scene": "receipt2"
  },
  {
    "word": "entrepreneur",
    "zh": "企業家、創業者",
    "rarity": "SSR",
    "origin": "法語",
    "route": "French entreprendre → entrepreneur",
    "root": "entre＝在…之間＋prendre＝拿、承擔",
    "story": "entrepreneur 原本就是「承擔一項工作的人」。後來逐漸專指承擔風險、組織資源創辦事業的人。",
    "tag": "商務",
    "scene": "entrepreneur"
  },
  {
    "word": "phenomenon",
    "zh": "現象",
    "rarity": "SR",
    "origin": "古希臘｜希臘語",
    "route": "phainomenon（顯現之物）→ phenomenon",
    "root": "phan＝顯現、出現",
    "story": "phenomenon 字面接近「顯現出來、能被觀察的東西」，因此成為科學與學術寫作中的現象。",
    "tag": "TOEFL",
    "scene": "phenomenon"
  },
  {
    "word": "theory",
    "zh": "理論",
    "rarity": "SR",
    "origin": "古希臘｜希臘語",
    "route": "theoria（觀看、思考）→ theory",
    "root": "theor＝觀看、思索",
    "story": "theoria 原本包含觀看與沉思的概念，後來 theory 成為用來解釋現象的一套系統化觀點。",
    "tag": "TOEFL",
    "scene": "theory"
  },
  {
    "word": "research",
    "zh": "研究",
    "rarity": "R",
    "origin": "法語",
    "route": "re + chercher（尋找）→ recherche → research",
    "root": "re＝再次＋search＝尋找",
    "story": "research 的構詞畫面就是反覆尋找、追查，因此很適合記成「不是找一次，而是再三查證」。",
    "tag": "TOEFL",
    "scene": "research"
  },
  {
    "word": "evidence",
    "zh": "證據",
    "rarity": "R",
    "origin": "拉丁語",
    "route": "evidentia → evidence",
    "root": "e/ex＝向外＋vid＝看",
    "story": "evidence 和 evident 都有「看得出來、顯而易見」的核心，因此是能讓事情被看清楚的證據。",
    "tag": "TOEFL",
    "scene": "evidence"
  },
  {
    "word": "university",
    "zh": "大學",
    "rarity": "SSR",
    "origin": "中世紀拉丁語",
    "route": "universitas → university",
    "root": "univers＝整體、共同體",
    "story": "universitas 在中世紀可指具有法律身分的共同體，後來特別用於教師與學生共同組成的學術社群。",
    "tag": "學術",
    "scene": "university"
  },
  {
    "word": "education",
    "zh": "教育",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "educare（養育、訓練）→ education",
    "root": "educ＝培育、引導",
    "story": "education 來自拉丁語培育與訓練的語義傳統，核心不是塞入知識，而是讓能力逐步成長。",
    "tag": "學術",
    "scene": "education"
  },
  {
    "word": "mathematics",
    "zh": "數學",
    "rarity": "SSR",
    "origin": "古希臘｜希臘語",
    "route": "mathema（學習、知識）→ mathematika → mathematics",
    "root": "math＝學習、知識",
    "story": "mathema 原本泛指所學到的知識，後來逐漸專門化成數量、結構與推理的數學。",
    "tag": "學術",
    "scene": "mathematics"
  },
  {
    "word": "geometry",
    "zh": "幾何學",
    "rarity": "SSR",
    "origin": "古希臘｜希臘語",
    "route": "geo（地）＋metron（測量）→ geometry",
    "root": "geo＝土地＋metr＝測量",
    "story": "geometry 字面就是「測量土地」。古代丈量土地的需求，成為幾何學名稱的來源。",
    "tag": "學術",
    "scene": "geometry"
  },
  {
    "word": "astronomy",
    "zh": "天文學",
    "rarity": "SSR",
    "origin": "古希臘｜希臘語",
    "route": "astron（星）＋nomos（規律）→ astronomy",
    "root": "astro＝星＋nom＝規則",
    "story": "astronomy 的構詞像是研究星辰的秩序與規律，因此成為天文學。",
    "tag": "科學",
    "scene": "astronomy"
  },
  {
    "word": "archaeology",
    "zh": "考古學",
    "rarity": "SSR",
    "origin": "古希臘｜希臘語",
    "route": "arkhaios（古老）＋logia（研究）→ archaeology",
    "root": "archae＝古老＋logy＝研究",
    "story": "archaeology 字面就是研究古老事物，透過遺址與器物重新理解過去的人類生活。",
    "tag": "學術",
    "scene": "archaeology"
  },
  {
    "word": "anthropology",
    "zh": "人類學",
    "rarity": "SSR",
    "origin": "古希臘｜希臘語",
    "route": "anthropos（人）＋logia（研究）→ anthropology",
    "root": "anthrop＝人類＋logy＝研究",
    "story": "anthropology 的構詞直接說明學科目的：系統研究人類、文化與社會。",
    "tag": "學術",
    "scene": "anthropology"
  },
  {
    "word": "linguistics",
    "zh": "語言學",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "lingua（舌、語言）→ linguistic → linguistics",
    "root": "lingu＝舌、語言",
    "story": "lingua 同時可指舌頭與語言，linguistics 因此成為研究語音、語法與語言系統的學科。",
    "tag": "學術",
    "scene": "linguistics"
  },
  {
    "word": "rhetoric",
    "zh": "修辭、修辭學",
    "rarity": "SR",
    "origin": "古希臘｜希臘語",
    "route": "rhetor（演說者）→ rhetorike → rhetoric",
    "root": "rhetor＝演說者",
    "story": "rhetoric 原本就是演說與說服的技藝，後來也用來分析語言如何影響聽眾。",
    "tag": "TOEFL",
    "scene": "rhetoric"
  },
  {
    "word": "memory",
    "zh": "記憶",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "memoria → memory",
    "root": "mem＝記住",
    "story": "memory 與 memo、memorize 同根，都圍繞「記住、提醒」這個核心概念。",
    "tag": "學術",
    "scene": "memory"
  },
  {
    "word": "cognition",
    "zh": "認知",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "cognoscere（認識、知道）→ cognition",
    "root": "co＝一起＋gn＝知道",
    "story": "cognition 指大腦取得、處理與使用知識的歷程，和 recognize、cognitive 共享「知道」的字源核心。",
    "tag": "學術",
    "scene": "cognition"
  },
  {
    "word": "neuron",
    "zh": "神經元",
    "rarity": "SR",
    "origin": "古希臘｜希臘語",
    "route": "neuron（神經、筋腱）→ neuron",
    "root": "neur＝神經",
    "story": "古希臘 neuron 可指神經或筋腱；現代神經科學借用它命名負責傳遞訊號的神經元。",
    "tag": "科學",
    "scene": "neuron"
  },
  {
    "word": "molecule",
    "zh": "分子",
    "rarity": "SR",
    "origin": "新拉丁語／法語",
    "route": "Latin moles（質量）→ molecula（小質量）→ molecule",
    "root": "mol＝質量、小塊",
    "story": "molecule 的名稱帶有「很小的一塊物質」的概念，後來成為化學中由原子組成的基本單位。",
    "tag": "科學",
    "scene": "molecule"
  },
  {
    "word": "gravity",
    "zh": "重力、嚴重性",
    "rarity": "SSR",
    "origin": "拉丁語",
    "route": "gravitas（重量、莊重）→ gravity",
    "root": "grav＝重",
    "story": "gravity 先有重量與莊重的語義，科學革命後也被用來表示物體彼此吸引的重力。",
    "tag": "科學",
    "scene": "gravity"
  },
  {
    "word": "climate",
    "zh": "氣候",
    "rarity": "SR",
    "origin": "古希臘｜希臘語",
    "route": "klima（傾斜、緯度帶）→ climate",
    "root": "clin＝傾斜",
    "story": "climate 的遠源和太陽照射角度、地球緯度帶有關，後來才發展成一地長期天氣型態。",
    "tag": "TOEFL",
    "scene": "climate"
  },
  {
    "word": "geology",
    "zh": "地質學",
    "rarity": "SR",
    "origin": "希臘語字根",
    "route": "geo（地球）＋logy（研究）→ geology",
    "root": "geo＝地球＋logy＝研究",
    "story": "geology 就是研究地球本身，特別是岩石、地層與地球歷史。",
    "tag": "科學",
    "scene": "geology"
  },
  {
    "word": "evolution",
    "zh": "演化、發展",
    "rarity": "SSR",
    "origin": "拉丁語",
    "route": "evolvere（展開卷軸）→ evolution",
    "root": "e＝向外＋volv＝捲、轉",
    "story": "evolution 原本有把卷軸逐步展開的畫面，後來被科學借來描述生物族群隨世代逐步改變。",
    "tag": "科學",
    "scene": "evolution"
  },
  {
    "word": "species",
    "zh": "物種、種類",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "species（外觀、種類）→ species",
    "root": "spec＝看",
    "story": "species 和 spect、inspect 的「看」同源，早期有外觀、種類之意，後來成為生物分類的基本單位。",
    "tag": "科學",
    "scene": "species"
  },
  {
    "word": "fossil",
    "zh": "化石",
    "rarity": "SSR",
    "origin": "拉丁語",
    "route": "fossilis（挖出的）→ fossil",
    "root": "fod/foss＝挖",
    "story": "fossil 原本泛指從地下挖出的東西，後來才逐漸專指保存下來的古代生物遺跡。",
    "tag": "科學",
    "scene": "fossil"
  },
  {
    "word": "habitat",
    "zh": "棲地",
    "rarity": "SR",
    "origin": "拉丁語",
    "route": "Latin habitat（它居住）→ habitat",
    "root": "habit＝居住、持有",
    "story": "habitat 原本是拉丁文「它居住」的形式，博物學家用它標記生物所在地，後來成為棲地。",
    "tag": "科學",
    "scene": "habitat"
  },
  {
    "word": "oxygen",
    "zh": "氧氣",
    "rarity": "UR",
    "origin": "18 世紀｜法語科學造字",
    "route": "Greek oxys（酸、銳）＋genes（產生）→ oxygène → oxygen",
    "root": "oxy＝酸、銳＋gen＝產生",
    "story": "oxygen 的名稱建立在早期「它會生成酸」的錯誤理論上。雖然理論後來被修正，名字卻保留下來。",
    "tag": "科學",
    "scene": "oxygen"
  },
  {
    "word": "constitution",
    "zh": "憲法、構成",
    "rarity": "SSR",
    "origin": "拉丁語",
    "route": "constituere（一起建立）→ constitution",
    "root": "con＝一起＋stitut＝建立、放置",
    "story": "constitution 的核心是把規則與制度「共同建立起來」，因此既可指構成，也可指國家的根本法。",
    "tag": "社會",
    "scene": "constitution"
  },
  {
    "word": "justice",
    "zh": "正義、司法",
    "rarity": "SSR",
    "origin": "拉丁語",
    "route": "iustitia → justice",
    "root": "jus＝法律、權利",
    "story": "justice 與 judge、juridical 同一個法律語源家族，核心是依法律與權利追求公平。",
    "tag": "社會",
    "scene": "justice"
  },
  {
    "word": "jury",
    "zh": "陪審團",
    "rarity": "SR",
    "origin": "古法語",
    "route": "juree（宣誓的一群人）→ jury",
    "root": "jur＝宣誓、法律",
    "story": "jury 的早期核心是「宣誓的人」。陪審員宣誓後共同判斷案件事實，因此形成現代制度名稱。",
    "tag": "社會",
    "scene": "jury"
  },
  {
    "word": "archive",
    "zh": "檔案、檔案館",
    "rarity": "SR",
    "origin": "古希臘｜希臘語",
    "route": "arkheion（政府公署、公共紀錄處）→ archive",
    "root": "arch＝統治、官署",
    "story": "archive 最早和保存官方紀錄的公共機構相關，後來泛指長期保存的重要文件與資料。",
    "tag": "學術",
    "scene": "archive"
  },
  {
    "word": "sandwich",
    "zh": "三明治",
    "rarity": "UR",
    "origin": "18 世紀｜英國人名",
    "route": "Earl of Sandwich → sandwich",
    "root": "來自 Sandwich 伯爵爵位名稱",
    "story": "sandwich 以第四代 Sandwich 伯爵 John Montagu 的爵位名稱聞名。把肉夾在麵包間方便食用的故事使這個名稱迅速流行。",
    "tag": "文化",
    "scene": "sandwich"
  },
  {
    "word": "boycott",
    "zh": "抵制",
    "rarity": "UR",
    "origin": "19 世紀｜人名",
    "route": "Charles Boycott → boycott",
    "root": "來自 Charles Boycott 姓氏",
    "story": "1880 年愛爾蘭土地爭議中，Charles Boycott 遭到社區集體拒絕往來，他的姓氏因此變成「抵制」這個動詞。",
    "tag": "歷史",
    "scene": "boycott"
  },
  {
    "word": "silhouette",
    "zh": "剪影、輪廓",
    "rarity": "UR",
    "origin": "18 世紀｜法國人名",
    "route": "Étienne de Silhouette → silhouette",
    "root": "來自法國官員姓氏",
    "story": "廉價的黑色側面剪影在 18 世紀被戲稱與 Étienne de Silhouette 有關，後來 silhouette 成為剪影與輪廓的正式名稱。",
    "tag": "文化",
    "scene": "silhouette"
  },
  {
    "word": "mentor",
    "zh": "導師、良師",
    "rarity": "UR",
    "origin": "古希臘文學｜人名",
    "route": "Homeric Mentor → mentor",
    "root": "來自《奧德賽》人物 Mentor",
    "story": "《奧德賽》中 Mentor 是 Odysseus 信任的友人與指導者，名字後來變成「導師」這個普通名詞。",
    "tag": "文化",
    "scene": "mentor"
  },
  {
    "word": "echo",
    "zh": "回聲",
    "rarity": "UR",
    "origin": "古希臘神話",
    "route": "Greek Ēkhō → echo",
    "root": "Echo＝神話中的回聲仙女",
    "story": "希臘神話中的 Echo 被迫只能重複別人的最後話語，她的名字因此和山谷中的回聲永遠連在一起。",
    "tag": "神話",
    "scene": "echo"
  },
  {
    "word": "atlas",
    "zh": "地圖集、阿特拉斯",
    "rarity": "UR",
    "origin": "古希臘神話／16 世紀地圖出版",
    "route": "Atlas → atlas",
    "root": "Atlas＝承擔天穹的泰坦神",
    "story": "Mercator 的 1595 年地圖著作使用 Atlas 之名，之後 atlas 逐漸成為成冊地圖集的通稱。",
    "tag": "文化",
    "scene": "atlas"
  }
]);
