window.ENROOT_CARDS=[
{word:"robot",zh:"機器人",rarity:"UR",origin:"1920｜捷克語",route:"Czech robota → robot",root:"robota＝強迫勞動、勞役",story:"robot 由捷克劇作家 Karel Čapek 的《R.U.R.》帶入世界。Čapek 後來表示，這個名稱是哥哥 Josef 建議的，來自 robota，原本指被迫從事的勞役。",tag:"科技"},
{word:"quarantine",zh:"隔離、檢疫",rarity:"UR",origin:"14–15 世紀｜義大利語",route:"Italian quaranta giorni / quarantena → quarantine",root:"quaranta＝四十",story:"歐洲港口為防疫曾要求來船隔離一段時間，威尼斯等地形成四十天隔離的制度與用語，後來演變成 quarantine。",tag:"歷史"},
{word:"vaccine",zh:"疫苗",rarity:"UR",origin:"18–19 世紀｜拉丁語",route:"Latin vacca（母牛）→ vaccinia → vaccine",root:"vacc＝牛",story:"Edward Jenner 以牛痘相關材料進行預防天花的實驗後，vaccine 這個字逐漸由「牛痘接種」擴展成今日所有疫苗的通稱。",tag:"科學"},
{word:"academy",zh:"學院、學術界",rarity:"UR",origin:"古希臘｜希臘語",route:"Greek Akadēmeia → Latin academia → academy",root:"Akadēmeia＝雅典城外地名",story:"柏拉圖在雅典附近的 Akadēmeia 講學。那個地方的名字後來一路變成「學院」與「學術界」的通稱。",tag:"學術"},
{word:"museum",zh:"博物館",rarity:"UR",origin:"古希臘｜希臘語",route:"Greek Mouseion → Latin museum",root:"Muse＝繆思女神",story:"Mouseion 原本是獻給繆思女神、供學術與藝術活動使用的場所。後來 museum 才逐漸固定成收藏與展示知識、藝術品的場所。",tag:"文化"},

{word:"candidate",zh:"候選人",rarity:"SSR",origin:"古羅馬｜拉丁語",route:"Latin candidatus → candidate",root:"candid＝白、明亮",story:"古羅馬競選公職者會穿特別潔白的 toga candida。candidatus 原意就是「穿白袍的人」，後來成為 candidate。",tag:"社會"},
{word:"panic",zh:"恐慌",rarity:"SSR",origin:"古希臘｜希臘語",route:"Greek Pan → panikos → panic",root:"Pan＝牧神潘",story:"古希臘人把荒野中突如其來、沒有明顯原因的恐懼與牧神 Pan 聯想在一起，因此形成表示「突然恐懼」的字。",tag:"神話"},
{word:"disaster",zh:"災難",rarity:"SSR",origin:"16 世紀｜義大利語",route:"Italian disastro → French désastre → disaster",root:"dis＝壞、相反＋astro＝星",story:"在占星觀念濃厚的年代，disastro 字面帶有「壞星象」的意味。後來不再限於星象，而泛指重大災難。",tag:"歷史"},
{word:"malaria",zh:"瘧疾",rarity:"SSR",origin:"18 世紀｜義大利語",route:"Italian mala aria → malaria",root:"mala＝壞＋aria＝空氣",story:"在病菌理論建立前，人們曾把沼澤地區疾病歸因於「壞空氣」，因此 mala aria 逐漸形成 malaria 這個疾病名稱。",tag:"醫學"},
{word:"salary",zh:"薪水",rarity:"SSR",origin:"拉丁語",route:"Latin salarium → Old French → salary",root:"sal＝鹽",story:"salary 來自拉丁文 salarium，與 sal「鹽」有詞源關係。古代鹽十分重要，但「羅馬士兵直接以鹽領薪」是後世常見的簡化說法，實際細節仍有爭議。",tag:"商務"},
{word:"alphabet",zh:"字母表",rarity:"SSR",origin:"古希臘｜希臘語",route:"alpha + beta → alphabet",root:"alpha＋beta＝希臘字母前兩字",story:"alphabet 直接把希臘字母表的前兩個字母 alpha、beta 合在一起，後來成為「字母表」的通稱。",tag:"語言"},
{word:"marathon",zh:"馬拉松",rarity:"SSR",origin:"19 世紀現代用法｜希臘地名",route:"Marathon（地名）→ marathon race",root:"Marathon＝希臘地名",story:"1896 年首屆現代奧運設計長距離賽事時，借用了「馬拉松戰役後信使奔跑」的傳說意象，marathon 因此成為長跑名稱。",tag:"運動"},

{word:"deadline",zh:"截止期限",rarity:"SR",origin:"19 世紀｜英語",route:"dead + line → deadline",root:"dead＋line",story:"deadline 在美國內戰時期曾指戰俘營內不可跨越的界線；之後語義轉為新聞出版與工作上「不能越過的最後期限」。",tag:"商務"},
{word:"broadcast",zh:"廣播、播送",rarity:"SR",origin:"18–20 世紀｜英語",route:"broad + cast → broadcast",root:"broad＝廣＋cast＝撒",story:"broadcast 原本是農業用語，指把種子「廣泛撒出去」。無線電興起後，這個畫面正好被借來形容把訊號傳向大量聽眾。",tag:"科技"},
{word:"companion",zh:"同伴",rarity:"SR",origin:"拉丁語／古法語",route:"Latin com + panis → Old French compagnon → companion",root:"com＝一起＋panis＝麵包",story:"companion 的深層構詞帶有「一起吃麵包的人」的概念，後來自然發展成同行者、夥伴。",tag:"生活"},
{word:"window",zh:"窗戶",rarity:"SR",origin:"古北歐語",route:"Old Norse vindauga → window",root:"vind＝風＋auga＝眼睛",story:"古北歐語 vindauga 字面是「風之眼」。這個形象後來進入英語，成為 window。",tag:"生活"},
{word:"enthusiasm",zh:"熱情",rarity:"SR",origin:"古希臘｜希臘語",route:"Greek enthousiasmos → enthusiasm",root:"en＝在內＋theos＝神",story:"enthusiasm 早期含有「神進入體內、受到神感」的宗教意味，後來才逐漸轉為強烈的熱情與投入。",tag:"情緒"},
{word:"calculate",zh:"計算",rarity:"SR",origin:"拉丁語",route:"Latin calculus（小石子）→ calculare → calculate",root:"calcul＝小石子",story:"古人會用小石子協助計數，因此 calculus「小石子」和計算概念連在一起，最後形成 calculate。",tag:"數學"},
{word:"school",zh:"學校",rarity:"SR",origin:"古希臘｜希臘語",route:"Greek scholē → Latin schola → school",root:"scholē＝閒暇、用於學習的時間",story:"scholē 原本可指閒暇。對古希臘自由民而言，有閒暇才能討論、學習與思考，語義後來逐漸走向「學校」。",tag:"學術"},
{word:"mortgage",zh:"抵押貸款",rarity:"SR",origin:"古法語",route:"Old French mort gage → mortgage",root:"mort＝死＋gage＝抵押、承諾",story:"mortgage 字面近似「死的抵押」。當債務履行或因違約終止時，這項抵押關係也就『死掉』，因而形成這個法律金融詞。",tag:"金融"},

{word:"transport",zh:"運輸",rarity:"R",origin:"拉丁語",route:"trans + portare → transport",root:"trans＝跨越＋port＝攜帶",story:"transport 的邏輯非常直接：把東西 carry across，從一處帶到另一處，因此成為運輸。",tag:"字根"},
{word:"inspect",zh:"檢查",rarity:"R",origin:"拉丁語",route:"in + specere → inspect",root:"in＝向內＋spect＝看",story:"inspect 就是「往裡看、仔細看」，所以從字根就能推到檢查、視察。",tag:"字根"},
{word:"predict",zh:"預測",rarity:"R",origin:"拉丁語",route:"prae + dicere → predict",root:"pre＝事前＋dict＝說",story:"predict 的核心畫面是「事情發生前先說出來」，因此是預測。",tag:"字根"},
{word:"portable",zh:"可攜式的",rarity:"R",origin:"拉丁語",route:"portare + able → portable",root:"port＝攜帶＋able＝可以",story:"portable 就是「可以被攜帶的」。抓到 port＝carry，import、export、transport 都會一起變簡單。",tag:"字根"},
{word:"audience",zh:"觀眾、聽眾",rarity:"R",origin:"拉丁語",route:"audire → audientia → audience",root:"aud＝聽",story:"audience 最初和『聽』密切相關，後來從聽者延伸成觀看表演或接收內容的一群人。",tag:"字根"},
{word:"manual",zh:"手動的、手冊",rarity:"R",origin:"拉丁語",route:"Latin manus → manualis → manual",root:"manu＝手",story:"manual 的核心就是 hand。手動操作叫 manual，供人親手操作時查閱的說明書也叫 manual。",tag:"字根"},

{word:"refund",zh:"退款",rarity:"N",origin:"拉丁語",route:"re + fundere → refund",root:"re＝回＋fund＝倒、支付",story:"refund 可把它記成「把錢送回去」。現代商務中就是退款。",tag:"商務"},
{word:"postpone",zh:"延後",rarity:"N",origin:"拉丁語",route:"post + ponere → postpone",root:"post＝後＋pon＝放",story:"postpone 就是「往後放」，因此自然表示延後。",tag:"字根"},
{word:"revenue",zh:"營收",rarity:"N",origin:"古法語／拉丁語",route:"revenir（返回）→ revenue",root:"re＝回＋ven＝來",story:"revenue 的遠源帶有「回來」的概念，後來用來指回到領主或組織手中的收入，成為營收。",tag:"商務"},
{word:"agenda",zh:"議程",rarity:"N",origin:"拉丁語",route:"Latin agenda → agenda",root:"ag＝做",story:"agenda 原本是拉丁語中「應該做的事情」的複數概念，後來成為會議上待處理事項的清單。",tag:"商務"}
,
{"word":"telephone","zh":"電話","rarity":"SSR","origin":"19 世紀｜希臘語字根","route":"tele（遠）＋phone（聲音）→ telephone","root":"tele＝遠＋phon＝聲音","story":"telephone 的構詞就是「把聲音送到遠方」。19 世紀電話技術成熟後，這個由希臘字根組成的新詞成為裝置名稱。","tag":"科技","scene":"phone"},
{"word":"television","zh":"電視","rarity":"SR","origin":"20 世紀初｜希臘語＋拉丁語","route":"tele（遠）＋vision（看）→ television","root":"tele＝遠＋vis＝看","story":"television 把希臘語的「遠」與拉丁語系的「看」接在一起，字面就是「從遠方看見」。","tag":"科技","scene":"screen"},
{"word":"microscope","zh":"顯微鏡","rarity":"SSR","origin":"17 世紀｜希臘語字根","route":"micro（小）＋scope（看）→ microscope","root":"micro＝微小＋scope＝看","story":"microscope 的名字直接描述功能：看見肉眼難以看清的微小事物。","tag":"科學","scene":"microscope"},
{"word":"biology","zh":"生物學","rarity":"SR","origin":"18–19 世紀｜希臘語字根","route":"bio（生命）＋logy（學科）→ biology","root":"bio＝生命＋logy＝學科","story":"biology 把「生命」和「研究學科」組合起來，成為研究生命現象的學科名稱。","tag":"學術","scene":"dna"},
{"word":"geography","zh":"地理學","rarity":"SR","origin":"古希臘｜希臘語","route":"geo（地球）＋graphy（書寫、描述）→ geography","root":"geo＝土地、地球＋graph＝寫","story":"geography 原本帶有「描述、書寫大地」的意思，因此成為研究地表與人地關係的學科名稱。","tag":"學術","scene":"globe"},
{"word":"chronology","zh":"年代學、時間順序","rarity":"SR","origin":"希臘語字根","route":"chronos（時間）＋logy（研究）→ chronology","root":"chron＝時間＋logy＝研究","story":"chronology 的核心就是把事件按時間排列，因此既能指年代學，也能指時間順序。","tag":"學術","scene":"clock"},
{"word":"photograph","zh":"照片、攝影","rarity":"SSR","origin":"19 世紀｜希臘語字根","route":"photo（光）＋graph（寫）→ photograph","root":"photo＝光＋graph＝寫、記錄","story":"photograph 字面可理解成「用光來寫」。早期攝影正是讓光在線性材料上留下影像。","tag":"科技","scene":"camera"},
{"word":"astronaut","zh":"太空人","rarity":"SSR","origin":"20 世紀｜希臘語字根","route":"astro（星）＋naut（航行者）→ astronaut","root":"astro＝星＋naut＝航行者","story":"astronaut 像是「星海中的航海者」，以古老的航海字根描述現代太空旅行者。","tag":"科學","scene":"rocket"},
{"word":"algorithm","zh":"演算法","rarity":"UR","origin":"中世紀｜阿拉伯數學傳統","route":"al-Khwarizmi 的拉丁化姓名 → algorism → algorithm","root":"來自數學家 al-Khwarizmi 的姓名","story":"algorithm 最終可追溯到波斯數學家 al-Khwarizmi 的姓名。人名經拉丁化後逐漸變成表示計算程序的方法名稱。","tag":"數學","scene":"numbers"},
{"word":"computer","zh":"電腦、計算機","rarity":"SR","origin":"17 世紀起｜拉丁語","route":"compute（計算）＋-er → computer","root":"comput＝計算","story":"computer 最初可以指「負責計算的人」。電子計算設備普及後，這個詞才主要指機器。","tag":"科技","scene":"computer"},
{"word":"internet","zh":"網際網路","rarity":"UR","origin":"20 世紀｜英語技術詞","route":"inter（彼此之間）＋network → internet","root":"inter＝在…之間＋net＝網","story":"internet 的概念就是把不同網路彼此連接，名稱本身就是 interconnected networks 的縮合思路。","tag":"科技","scene":"network"},
{"word":"satellite","zh":"衛星","rarity":"SR","origin":"拉丁語","route":"Latin satelles（隨從、護衛）→ satellite","root":"satelles＝隨從","story":"satellite 原先不是天文詞，而有「隨從」的意思。因為衛星伴隨行星運行，後來被借來命名天體。","tag":"科學","scene":"satellite"},
{"word":"electricity","zh":"電、電力","rarity":"SSR","origin":"17 世紀｜希臘語","route":"Greek elektron（琥珀）→ electric → electricity","root":"elektron＝琥珀","story":"古人發現摩擦琥珀會吸引細小物體。後來研究這種現象時，與琥珀相關的字逐漸成為 electricity 的來源。","tag":"科學","scene":"lightning"},
{"word":"laboratory","zh":"實驗室","rarity":"SR","origin":"拉丁語","route":"labor（工作）→ laboratorium → laboratory","root":"labor＝工作","story":"laboratory 原意接近「工作的場所」，之後特別固定成進行實驗與研究的空間。","tag":"科學","scene":"flask"},
{"word":"chemistry","zh":"化學","rarity":"SR","origin":"中世紀阿拉伯語與希臘語傳統","route":"alchemy / al-kīmiyāʾ → chemistry","root":"與 alchemy 的歷史詞源相連","story":"chemistry 與 alchemy 共享歷史詞源。隨著實驗方法與現代科學建立，名稱逐漸脫離煉金術而成為現代化學。","tag":"科學","scene":"flask"},
{"word":"physics","zh":"物理學","rarity":"SR","origin":"古希臘｜希臘語","route":"physis（自然）→ physika → physics","root":"phys＝自然、生長","story":"physics 源自研究「自然」的概念，後來成為研究物質、能量與基本規律的學科名稱。","tag":"學術","scene":"atom"},
{"word":"ecology","zh":"生態學","rarity":"SR","origin":"19 世紀｜希臘語字根","route":"oikos（家、環境）＋logy（研究）→ ecology","root":"eco＝家、環境＋logy＝研究","story":"ecology 的深層畫面是「研究生物的家」，因此延伸為生物與環境關係的研究。","tag":"學術","scene":"leaf"},
{"word":"anatomy","zh":"解剖學","rarity":"SR","origin":"古希臘｜希臘語","route":"ana（向上、分開）＋tome（切）→ anatomy","root":"tom＝切","story":"anatomy 的詞源和「切開觀察」有關，正好對應解剖學以結構觀察理解身體。","tag":"醫學","scene":"body"},
{"word":"psychology","zh":"心理學","rarity":"SSR","origin":"希臘語字根","route":"psyche（心靈）＋logy（研究）→ psychology","root":"psych＝心靈＋logy＝研究","story":"psychology 字面是「研究心靈」，後來成為研究行為與心智歷程的現代學科。","tag":"學術","scene":"brain"},
{"word":"sociology","zh":"社會學","rarity":"SR","origin":"19 世紀｜拉丁語＋希臘語","route":"socius（同伴、社會）＋logy → sociology","root":"soci＝夥伴、社會＋logy＝研究","story":"sociology 將「社會、同伴」與「研究」結合，用來描述系統研究社會關係的學科。","tag":"學術","scene":"people"},
{"word":"democracy","zh":"民主","rarity":"UR","origin":"古希臘｜希臘語","route":"demos（人民）＋kratos（統治、權力）→ democracy","root":"demo＝人民＋cracy＝統治","story":"democracy 的構詞非常直白：人民的權力或統治。這個古希臘政治詞一路沿用到現代。","tag":"歷史","scene":"ballot"},
{"word":"philosophy","zh":"哲學","rarity":"SSR","origin":"古希臘｜希臘語","route":"philo（愛）＋sophia（智慧）→ philosophy","root":"phil＝愛＋soph＝智慧","story":"philosophy 字面是「愛智慧」。這個名稱把追求知識與智慧本身當成一種生活方式。","tag":"學術","scene":"thinker"},
{"word":"hypothesis","zh":"假說","rarity":"SR","origin":"古希臘｜希臘語","route":"hypo（在下）＋thesis（放置、主張）→ hypothesis","root":"hypo＝在下＋thesis＝放置、主張","story":"hypothesis 原本有「放在底下作為基礎」的感覺，後來成為等待證據檢驗的暫時性解釋。","tag":"學術","scene":"experiment"},
{"word":"analysis","zh":"分析","rarity":"R","origin":"古希臘｜希臘語","route":"ana（分開）＋lysis（鬆解）→ analysis","root":"ana＝分開＋lys＝鬆開","story":"analysis 的核心畫面是把整體拆開、鬆解成部分來理解。","tag":"學術","scene":"split"},
{"word":"synthesis","zh":"綜合、合成","rarity":"R","origin":"古希臘｜希臘語","route":"syn（一起）＋thesis（放置）→ synthesis","root":"syn＝一起＋thesis＝放置","story":"synthesis 和 analysis 幾乎是相反方向：把不同部分重新放在一起形成整體。","tag":"學術","scene":"merge"},
{"word":"library","zh":"圖書館","rarity":"SSR","origin":"拉丁語","route":"liber（書）→ librarium / libraria → library","root":"libr＝書","story":"library 的詞源核心直接和「書」相連，從藏書之處逐漸成為今日圖書館。","tag":"文化","scene":"books"},
{"word":"theatre","zh":"劇院、戲劇","rarity":"SSR","origin":"古希臘｜希臘語","route":"theatron（觀看的地方）→ theatre","root":"thea＝看","story":"theatre 原本就是「觀看的地方」，因此從觀眾席與表演空間發展成戲劇與劇院的名稱。","tag":"文化","scene":"stage"},
{"word":"music","zh":"音樂","rarity":"SR","origin":"古希臘｜希臘語","route":"mousikē（繆思女神的藝術）→ musica → music","root":"Muse＝繆思女神","story":"music 早期與繆思女神所掌管的藝術相連，後來逐漸專指聲音與旋律的藝術。","tag":"文化","scene":"music"},
{"word":"history","zh":"歷史","rarity":"SR","origin":"古希臘｜希臘語","route":"historia（探究、調查所得知識）→ history","root":"histor＝知道、探究","story":"history 原本帶有「探究、調查」的意思，不只是過去，而是透過查證來理解過去。","tag":"學術","scene":"scroll"},
{"word":"literature","zh":"文學","rarity":"SR","origin":"拉丁語","route":"littera（字母）→ litteratura → literature","root":"liter＝字母、文字","story":"literature 的詞源核心是字母與書寫，後來才發展成文學作品與相關研究的總稱。","tag":"文化","scene":"book"},
{"word":"language","zh":"語言","rarity":"R","origin":"拉丁語／古法語","route":"lingua（舌頭、語言）→ langage → language","root":"lingu＝舌頭、語言","story":"language 的遠源與「舌頭」相連，因為說話器官自然成為語言能力的象徵。","tag":"語言","scene":"speech"},
{"word":"contract","zh":"合約","rarity":"SR","origin":"拉丁語","route":"con（一起）＋trahere（拉）→ contract","root":"con＝一起＋tract＝拉","story":"contract 原本有「拉在一起、收縮」的感覺；在法律上則像把雙方義務拉到同一份約定中。","tag":"商務","scene":"contract"},
{"word":"invoice","zh":"發票、請款單","rarity":"R","origin":"中古法語","route":"envois / envoyer（送出）相關詞源 → invoice","root":"與「送出貨物或清單」的商業用語相連","story":"invoice 的歷史和貨物被送出時附帶的清單、帳目有關，後來固定成請款文件。","tag":"商務","scene":"receipt"},
{"word":"budget","zh":"預算","rarity":"SR","origin":"古法語","route":"bougette（小皮袋）→ budget","root":"bougette＝小袋子","story":"budget 原本是裝錢的小皮袋。政府財務文件曾從「袋子裡拿出來」，名稱後來轉為預算本身。","tag":"金融","scene":"coins"},
{"word":"finance","zh":"財務、金融","rarity":"R","origin":"中古法語／拉丁語","route":"fin（結束、結清）→ finance","root":"fin＝結束、結清","story":"finance 的遠源和「結清、完成付款」有關，後來逐漸擴大為管理金錢與資本的概念。","tag":"金融","scene":"bank"},
{"word":"credit","zh":"信用、貸方","rarity":"R","origin":"拉丁語","route":"credere（相信）→ credit","root":"cred＝相信","story":"credit 的核心是 trust：願意先給你資源，是因為相信你之後會履行承諾。","tag":"金融","scene":"card"},
{"word":"debit","zh":"借方、扣款","rarity":"R","origin":"拉丁語","route":"debere（欠）→ debit","root":"deb＝欠","story":"debit 與「所欠之物」的概念相連，因此成為會計中記錄支出或借方的詞。","tag":"金融","scene":"card"},
{"word":"negotiate","zh":"協商、談判","rarity":"SR","origin":"拉丁語","route":"neg（不）＋otium（閒暇）→ negotium（事務、商業）→ negotiate","root":"neg＝不＋otium＝閒暇","story":"negotium 字面近似「不是閒暇」，也就是要處理的事務。後來 negotiate 逐漸專指協商與談判。","tag":"商務","scene":"handshake"},
{"word":"corporation","zh":"公司、法人團體","rarity":"SR","origin":"拉丁語","route":"corpus（身體）→ corporare（形成一體）→ corporation","root":"corp＝身體、整體","story":"corporation 把多人組織想成一個「身體」，法律上也因此能作為一個整體行動。","tag":"商務","scene":"building"},
{"word":"company","zh":"公司、同伴","rarity":"SR","origin":"拉丁語／古法語","route":"com（一起）＋panis（麵包）→ compagnie → company","root":"com＝一起＋pan＝麵包","story":"company 與 companion 同源，深層畫面都是「一起吃麵包的人」，再延伸成一起工作的一群人。","tag":"商務","scene":"people"},
{"word":"capital","zh":"資本、首都","rarity":"SR","origin":"拉丁語","route":"caput（頭）→ capitalis → capital","root":"cap＝頭","story":"capital 的核心是「頭、主要」。因此既可指一國的主要城市，也可指經濟活動中的主要資本。","tag":"金融","scene":"tower"},
{"word":"market","zh":"市場","rarity":"R","origin":"拉丁語／古法語","route":"mercatus（交易、市場）→ market","root":"merc＝交易","story":"market 自古就和交易場所相連，後來也可抽象指某類商品或服務的整體需求與供給。","tag":"商務","scene":"market"},
{"word":"commerce","zh":"商業、貿易","rarity":"R","origin":"拉丁語","route":"com（一起）＋merx（商品）→ commercium → commerce","root":"com＝一起＋merc＝商品、交易","story":"commerce 的畫面就是人們把商品聚在一起交換，因此成為商業與貿易的總稱。","tag":"商務","scene":"cart"},
{"word":"purchase","zh":"購買","rarity":"N","origin":"古法語","route":"pourchacier（追求、設法取得）→ purchase","root":"早期含「努力取得」之意","story":"purchase 原先不只表示付錢，還帶有「設法取得」的意思，後來才逐漸固定成購買。","tag":"商務","scene":"cart"},
{"word":"export","zh":"出口、輸出","rarity":"R","origin":"拉丁語","route":"ex（向外）＋portare（攜帶）→ export","root":"ex＝向外＋port＝攜帶","story":"export 就是「把東西帶出去」，字根畫面和現代出口完全一致。","tag":"商務","scene":"shipout"},
{"word":"import","zh":"進口、輸入","rarity":"R","origin":"拉丁語","route":"im/in（向內）＋portare（攜帶）→ import","root":"im＝向內＋port＝攜帶","story":"import 就是「把東西帶進來」，與 export 成為最好記的一對。","tag":"商務","scene":"shipin"},
{"word":"recruit","zh":"招募、新兵","rarity":"R","origin":"法語","route":"recrue（新增加的人員）→ recruit","root":"re＝再次、新增＋相關於增補人員","story":"recruit 的歷史和補充隊伍人數有關，後來擴展到公司招募新成員。","tag":"人資","scene":"recruit"},
{"word":"interview","zh":"面試、訪談","rarity":"R","origin":"法語","route":"entre（彼此之間）＋voir（看）→ entrevue → interview","root":"inter＝彼此之間＋view＝看","story":"interview 原先帶有「彼此見面」的概念，因此很自然地發展成訪談與面試。","tag":"人資","scene":"chat"},
{"word":"applicant","zh":"申請人","rarity":"N","origin":"拉丁語","route":"applicare（靠近、投入）→ apply → applicant","root":"ap/ad＝向＋plic＝折、貼","story":"apply 原本有「貼上、投入」的概念，後來成為提出申請；提出申請的人就是 applicant。","tag":"人資","scene":"persondoc"},
{"word":"promotion","zh":"升遷、促銷","rarity":"R","origin":"拉丁語","route":"pro（向前）＋movere（移動）→ promotion","root":"pro＝向前＋mot＝移動","story":"promotion 的核心畫面是「往前移」，因此既能表示職位升遷，也能表示把商品往市場前方推。","tag":"商務","scene":"arrowup"},
{"word":"management","zh":"管理","rarity":"R","origin":"義大利語／法語","route":"mano（手）相關 → manage → management","root":"man＝手","story":"manage 的早期語義曾和「用手控制、駕馭」相連，後來轉為管理人、資源與組織。","tag":"商務","scene":"manager"},
{"word":"warranty","zh":"保固、保證","rarity":"R","origin":"古法語／日耳曼語源","route":"warant（保護、保證者）→ warranty","root":"warant＝保證、保護","story":"warranty 的核心一直和「有人願意為結果擔保」相連，現代商品保固延續了這個概念。","tag":"商務","scene":"shield"},
{"word":"inventory","zh":"庫存、存貨清單","rarity":"R","origin":"拉丁語","route":"invenire（找到）→ inventarium（清單）→ inventory","root":"in＝進入＋ven＝來、找到","story":"inventory 曾指被找到、被記錄的物品清單，後來固定成庫存與盤點清單。","tag":"物流","scene":"boxes"},
{"word":"logistics","zh":"物流、後勤","rarity":"SR","origin":"希臘語／法語軍事用語","route":"logistikos（計算）→ logistique → logistics","root":"log＝計算、推理","story":"logistics 在軍事中重視精確計算補給與運輸，後來擴展到企業的物流與供應鏈管理。","tag":"物流","scene":"truck"},
{"word":"project","zh":"專案、投射","rarity":"R","origin":"拉丁語","route":"pro（向前）＋jacere（投）→ project","root":"pro＝向前＋ject＝投","story":"project 的核心是「向前投出去」。一個專案就像把計畫投向未來，逐步落實。","tag":"商務","scene":"blueprint"},
{"word":"strategy","zh":"策略","rarity":"SR","origin":"古希臘｜希臘語","route":"strategos（將軍）→ strategia → strategy","root":"stratos＝軍隊＋agos＝領導","story":"strategy 原本是將軍指揮軍隊的藝術，後來延伸成任何需要長期布局的策略。","tag":"商務","scene":"chess"},
{"word":"economy","zh":"經濟","rarity":"SR","origin":"古希臘｜希臘語","route":"oikos（家）＋nomos（管理、規則）→ oikonomia → economy","root":"eco/oiko＝家＋nom＝管理、規則","story":"economy 最初的畫面其實是「管理一個家」。後來尺度放大，成為管理國家與資源的概念。","tag":"學術","scene":"coins"},
{"word":"conference","zh":"會議","rarity":"R","origin":"拉丁語","route":"con（一起）＋ferre（帶）→ confer → conference","root":"con＝一起＋fer＝帶","story":"conference 的構詞像是「把意見帶到一起」，因此成為多人交換資訊與討論的會議。","tag":"商務","scene":"meeting"},
{"word":"construct","zh":"建造、構成","rarity":"R","origin":"拉丁語","route":"con（一起）＋struere（堆疊）→ construct","root":"con＝一起＋struct＝建造、堆疊","story":"construct 就像把材料一層層堆在一起，所以表示建造，也能表示構成概念。","tag":"字根","scene":"bricks"},
{"word":"interrupt","zh":"打斷、中斷","rarity":"R","origin":"拉丁語","route":"inter（在中間）＋rumpere（打破）→ interrupt","root":"inter＝在中間＋rupt＝破","story":"interrupt 就是「從中間把流程打破」，因此是打斷與中斷。","tag":"字根","scene":"chain"},
{"word":"erupt","zh":"爆發、噴發","rarity":"R","origin":"拉丁語","route":"e/ex（向外）＋rumpere（破裂）→ erupt","root":"e＝向外＋rupt＝破裂","story":"erupt 的畫面就是「破開往外衝」，非常適合記火山噴發與突然爆發。","tag":"字根","scene":"volcano"},
{"word":"submit","zh":"提交、服從","rarity":"R","origin":"拉丁語","route":"sub（在下）＋mittere（送）→ submit","root":"sub＝在下＋mit＝送","story":"submit 原本帶有「送到下方、置於權威之下」的概念，因此既能表示提交，也能表示服從。","tag":"字根","scene":"inbox"},
{"word":"permit","zh":"允許、許可","rarity":"R","origin":"拉丁語","route":"per（通過）＋mittere（送）→ permit","root":"per＝通過＋mit＝送","story":"permit 像是「讓事情通過」，因此成為允許與許可。","tag":"字根","scene":"key"},
{"word":"emit","zh":"發出、排放","rarity":"R","origin":"拉丁語","route":"e/ex（向外）＋mittere（送）→ emit","root":"e＝向外＋mit＝送","story":"emit 就是「向外送出」，所以光、聲音、氣體都可以被 emitted。","tag":"字根","scene":"send"},
{"word":"accept","zh":"接受","rarity":"N","origin":"拉丁語","route":"ad（向）＋capere（拿）→ accept","root":"ac/ad＝向＋cept＝拿、接受","story":"accept 的核心像是「把東西拿到自己這邊」，因此是接受。","tag":"字根","scene":"receive"},
{"word":"receive","zh":"收到、接收","rarity":"N","origin":"拉丁語","route":"re（回、向後）＋capere（拿）→ receive","root":"re＝回＋ceive/cept＝拿","story":"receive 和 accept 都保留「拿、接」的概念，重點是東西來到你手上。","tag":"字根","scene":"receive"},
{"word":"retain","zh":"保留、保持","rarity":"N","origin":"拉丁語","route":"re（回、持續）＋tenere（握住）→ retain","root":"re＝持續＋tain/ten＝握住","story":"retain 就是「繼續握住不放」，因此是保留與保持。","tag":"字根","scene":"hold"},
{"word":"contain","zh":"包含、容納","rarity":"N","origin":"拉丁語","route":"con（一起）＋tenere（握住）→ contain","root":"con＝一起＋tain＝握住","story":"contain 像是把東西「一起握在範圍裡」，因此表示包含與容納。","tag":"字根","scene":"box"},
{"word":"position","zh":"位置、職位","rarity":"N","origin":"拉丁語","route":"ponere（放置）→ positio → position","root":"pos/pon＝放置","story":"position 的核心就是「被放在哪裡」，因此可以是物理位置，也可以是組織中的職位。","tag":"字根","scene":"pin"},
{"word":"progress","zh":"進步、進展","rarity":"R","origin":"拉丁語","route":"pro（向前）＋gradi（走）→ progress","root":"pro＝向前＋gress＝走","story":"progress 就是「往前走」，因此成為進展與進步最直觀的字根例子。","tag":"字根","scene":"stairs"}
];
